
spring.datasource.url=jdbc:postgresql://168.107.27.186:5432/woori
spring.datasource.username=woori
spring.datasource.password=${OCI_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-update.sql

climate.service-key=${KMA_SERVICE_KEY}


public-data.service-key=L%2BpdidGDiHmJocidUdwlj7YlSFW0bosJ4RqLlVeCw7yhZQfx4WLiM1Q3vQXHRbGOVfnxFH8s5c40Xz%2BvgvQeTg%3D%3D

# OCI PostgreSQL connection pool limit
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
