server.port=8181

spring.jpa.hibernate.ddl-auto=update

# ???
police.safe182.esntl-id=10000931
police.safe182.auth-key=7cc9a93695174657

# ?? ?? ??
gemini.api.key=AIzaSyBX-C4uTjYzd6KaQIy86_CcvnzArS8ZEas
gemini.embedding.model=gemini-embedding-001

groq.api.key=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
groq.chat.model=llama-3.3-70b-versatile

data.api.service-key=L%2BpdidGDiHmJocidUdwlj7YlSFW0bosJ4RqLlVeCw7yhZQfx4WLiM1Q3vQXHRbGOVfnxFH8s5c40Xz%2BvgvQeTg%3D%3D
public-data.welfare-base-url=https://apis.data.go.kr/B554287/LocalGovernmentWelfareInformations