server.port=8181


spring.jpa.hibernate.ddl-auto=update

police.safe182.esntl-id=${SAFE182_ESNTL_ID}
police.safe182.auth-key=${SAFE182_AUTH_KEY}


# Aiven PostgreSQL connection pool limit
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

spring.datasource.hikari.connection-timeout=30000

