spring.datasource.url=jdbc:postgresql://ep-bitter-resonance-aocko3es.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=woori2026dbpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:neon-schema-update.sql

climate.service-key=${KMA_SERVICE_KEY:M1FEdIziwexRX6M%2BKOI2PolaM4N3Hr6gNs3Dd26lwB202guC%2B2hsoMRPlmN0g%2FFPF3YvFT0WEf99ZYNyb22rKQ%3D%3D}

gemini.api-key=AIzaSyCijjNzitbday4kG_sbZzdbgotWzS2xNVY
gemini.generate-model=gemini-2.5-flash-lite
gemini.embedding-model=gemini-embedding-001

public-data.welfare-service-key=L%2BpdidGDiHmJocidUdwlj7YlSFW0bosJ4RqLlVeCw7yhZQfx4WLiM1Q3vQXHRbGOVfnxFH8s5c40Xz%2BvgvQeTg%3D%3D
public-data.welfare-list-url=https://apis.data.go.kr/B554287/LocalGovernmentWelfareInformations/LcgvWelfarelist?serviceKey={serviceKey}&pageNo={pageNo}&numOfRows={numOfRows}
public-data.welfare-detail-url=https://apis.data.go.kr/B554287/LocalGovernmentWelfareInformations/LcgvWelfaredetailed?serviceKey={serviceKey}&servId={serviceId}

groq.api.key=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
groq.chat.model=llama-3.3-70b-versatile

data.api.service-key=L%2BpdidGDiHmJocidUdwlj7YlSFW0bosJ4RqLlVeCw7yhZQfx4WLiM1Q3vQXHRbGOVfnxFH8s5c40Xz%2BvgvQeTg%3D%3D

