
spring.datasource.url=jdbc:postgresql://168.107.27.186:5432/woori
spring.datasource.username=woori
spring.datasource.password=${OCI_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-update.sql

climate.service-key=${KMA_SERVICE_KEY:}


public-data.service-key=${PUBLIC_DATA_SERVICE_KEY:}

police.safe182.esntl-id=${SAFE182_ESNTL_ID:10000931}
police.safe182.auth-key=${SAFE182_AUTH_KEY:7cc9a93695174657}

# RAG
ai.backend.base-url=${AI_BACKEND_BASE_URL:http://127.0.0.1:8001/api}

# face
app.face-server-url=${FACE_SERVER_URL:http://localhost:8003}

app.upload-root=${APP_UPLOAD_ROOT:uploads}

app.medication-alert.auto-enabled=true

firebase.service-account-path=${FIREBASE_SERVICE_ACCOUNT_PATH:}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# OCI PostgreSQL connection pool limit
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
