name: woori_senior_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter_dotenv: ^5.2.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3   
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: 2.3.0
  geolocator: ^13.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  image_picker: ^1.1.2
  mime: ^1.0.6
  speech_to_text: ^7.4.0
  flutter_tts: ^3.8.5

  kakao_map_plugin: ^0.4.0

  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

# 앱 아이콘 설정
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/senior_icon.png"
  min_sdk_android: 21
  # 보호자 앱 아이콘 배경과 동일한 색
  adaptive_icon_background: "#80937B"
  adaptive_icon_foreground: "assets/icon/senior_icon_fg.png"
  web:
    generate: false

# 스플래시 설정
flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/senior_splash.png
  android: true
  ios: true
  fullscreen: true
  android_12:
    color: "#ffffff"
    image: assets/splash/senior_splash.png

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/icon/
    - assets/splash/