package com.nuri.woorilink.service;
import com.fasterxml.jackson.databind.*;import com.nuri.woorilink.common.client.SafetyKoreaRecallClient;import com.nuri.woorilink.entity.RecallNotice;import com.nuri.woorilink.repository.RecallNoticeRepository;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import java.util.regex.Pattern;
@Service @RequiredArgsConstructor
public class RecallNoticeStore {
 private static final Pattern SCOPE=Pattern.compile("제조.{0,8}(기간|일자)|생산.{0,8}(기간|일자)|시리얼|제조번호|로트|LOT|색상|크기|사이즈|판매기간|일부 모델",Pattern.CASE_INSENSITIVE);
 private final RecallNoticeRepository repo;private final ObjectMapper mapper;private final RecallActionClassifier actionClassifier;
 @Transactional public List<RecallNotice>save(List<SafetyKoreaRecallClient.NoticePayload>payloads){List<RecallNotice>out=new ArrayList<>();for(var p:payloads)out.add(saveOne(p));return out;}
 private RecallNotice saveOne(SafetyKoreaRecallClient.NoticePayload p){LocalDateTime now=LocalDateTime.now();RecallNotice n=repo.findByRecallUid(p.recallUid()).orElseGet(()->RecallNotice.builder().recallUid(p.recallUid()).firstSyncedAt(now).build());JsonNode l=p.listItem(),d=p.detailItem();n.setProductName(first(d,l,"recallProductName"));n.setBrandName(first(d,l,"recallBrandName"));n.setManufacturerName(first(d,l,"makerName"));n.setRecallCompanyName(first(d,l,"recallCmpnyName"));n.setModelNames(split(first(d,l,"recallModelName")));n.setBarcodeNumbers(split(first(d,l,"barcodeNum")));n.setCertNumbers(split(nonBlank(first(d,l,"certNum"))?first(d,l,"certNum"):first(d,l,"certificationNum")));n.setProductCategory(first(d,l,"productCategoryName"));n.setPublishDate(date(first(d,l,"publishDate")));n.setRecallStartDate(date(first(d,l,"recallStaDate")));n.setRecallEndDate(date(first(d,l,"recallEndDate")));n.setDefectDescription(nonBlank(first(d,l,"harmDscr"))?first(d,l,"harmDscr"):first(d,l,"violateDscr"));n.setHazardDescription(first(d,l,"accidentCaseDscr"));n.setConsumerAction(nonBlank(first(d,l,"publishActionDscr"))?first(d,l,"publishActionDscr"):first(d,l,"recallMeans"));n.setActionType(actionClassifier.classify(n.getConsumerAction()));n.setInquiryTel(first(d,l,"recallInqryTel"));n.setImageUrls(split(first(d,l,"imageUrl")));String scope=String.join("\n",List.of(safe(n.getDefectDescription()),safe(n.getHazardDescription()),safe(n.getConsumerAction())));n.setAdditionalConditionText(scope);n.setHasUnstructuredScopeCondition(p.detailFailed()||SCOPE.matcher(scope).find());n.setSourceUrl("https://www.safetykorea.kr/recall/ajax/recallBoard?recallUid="+p.recallUid());n.setListRawResponse(json(l));n.setDetailRawResponse(json(d));n.setContentHash(hash(n.getListRawResponse()+n.getDetailRawResponse()));n.setLastSyncedAt(now);n.setActive(true);return repo.save(n);}
 private String first(JsonNode a,JsonNode b,String f){String v=text(a,f);return v.isBlank()?text(b,f):v;}private String text(JsonNode n,String f){JsonNode v=n==null?null:n.get(f);return v==null||v.isNull()?"":v.asText("").trim();}private List<String>split(String v){if(!nonBlank(v))return new ArrayList<>();return new ArrayList<>(new LinkedHashSet<>(Arrays.stream(v.split("[,;/|\\n\\r]")).map(String::trim).filter(x->!x.isBlank()).toList()));}private LocalDate date(String v){for(String p:List.of("yyyyMMdd","yyyy-MM-dd"))try{return LocalDate.parse(v,DateTimeFormatter.ofPattern(p));}catch(Exception ignored){}return null;}private String json(JsonNode n){try{return mapper.writeValueAsString(n);}catch(Exception e){return"{}";}}private String hash(String v){try{byte[]d=MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8));return HexFormat.of().formatHex(d);}catch(Exception e){throw new IllegalStateException(e);}}private boolean nonBlank(String v){return v!=null&&!v.isBlank();}private String safe(String v){return v==null?"":v;}
}
