package com.nuri.woorilink.service;
import com.nuri.woorilink.common.client.SafetyKoreaRecallClient;import com.nuri.woorilink.common.config.RecallSafetyProperties;import com.nuri.woorilink.entity.*;import com.nuri.woorilink.repository.*;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;import java.util.*;
@Service @RequiredArgsConstructor
public class RecallSafetyService {
 private final RegisteredProductRepository products;private final SafetyKoreaRecallClient client;private final RecallNoticeStore store;private final RecallDecisionEngine engine;private final ProductRecallCheckHistoryRepository histories;private final ProductRecallAlertRepository alerts;private final RecallSafetyProperties properties;
 public boolean enabled(){return properties.isNewDecisionEngineEnabled();}
 @Transactional public RegisteredProduct check(Long id){RegisteredProduct p=products.findById(id).orElseThrow(()->new IllegalArgumentException("등록 제품을 찾을 수 없습니다: "+id));LocalDateTime now=LocalDateTime.now();var lookup=client.lookup(new SafetyKoreaRecallClient.ProductQuery(p.getProductName(),p.getManufacturer(),p.getModelNumber(),effectiveBarcode(p),p.getCertificationNumber()));
  if(!lookup.success()){p.setRecallCheckStatus(RegisteredProduct.RecallCheckStatus.FAILED);p.setLastCheckedAt(now);p.setLastCheckFailedAt(now);p.setLastCheckErrorCode(lookup.errorCode());p.setLastCheckErrorMessage(lookup.errorMessage());products.save(p);history(p,null,p.getRecallDecisionStatus(),RegisteredProduct.RecallCheckStatus.FAILED,List.of(),List.of(),List.of(),List.of(),p.getRecallDecisionReason(),null,null,lookup);return p;}
  List<RecallNotice>candidates=store.save(lookup.notices());var d=engine.decide(p,candidates);RegisteredProduct.RecallDecisionStatus previous=p.getRecallDecisionStatus();
  if(previous==RegisteredProduct.RecallDecisionStatus.RECALL_CONFIRMED&&d.status()!=RegisteredProduct.RecallDecisionStatus.RECALL_CONFIRMED){p.setRecallCheckStatus(RegisteredProduct.RecallCheckStatus.SUCCESS);p.setLastCheckedAt(now);p.setLastSuccessfulCheckedAt(now);p.setRecallMissingFields(List.of("ADMINISTRATOR_REVIEW"));p.setRecallDecisionReason("기존 확정 공고가 새 조회에서 확인되지 않아 기존 확정 판정을 유지합니다.");products.save(p);history(p,p.getMatchedRecallNoticeId(),previous,RegisteredProduct.RecallCheckStatus.SUCCESS,p.getRecallMatchedFields(),List.of(),p.getRecallMissingFields(),d.candidateUids(),p.getRecallDecisionReason(),d.queryType(),d.queryValue(),lookup);return p;}
  p.setRecallDecisionStatus(d.status());p.setRecallCheckStatus(RegisteredProduct.RecallCheckStatus.SUCCESS);p.setMatchedRecallNoticeId(d.notice()==null?null:d.notice().getId());p.setRecallDecisionReason(d.reason());p.setRecallMatchedFields(d.matched());p.setRecallMissingFields(d.missing());p.setLastCheckedAt(now);p.setLastSuccessfulCheckedAt(now);p.setLastCheckErrorCode(null);p.setLastCheckErrorMessage(null);
  p.setRecallStatus(switch(d.status()){case RECALL_CONFIRMED->RegisteredProduct.RecallStatus.RECALLED;case NO_MATCH_FOUND->RegisteredProduct.RecallStatus.SAFE;case REVIEW_REQUIRED->RegisteredProduct.RecallStatus.UNKNOWN;});p.setModelMatchStatus(switch(d.status()){case RECALL_CONFIRMED->RegisteredProduct.ModelMatchStatus.MATCHED;case NO_MATCH_FOUND->RegisteredProduct.ModelMatchStatus.NOT_MATCHED;case REVIEW_REQUIRED->RegisteredProduct.ModelMatchStatus.NEEDS_REVIEW;});p.setRecallReason(legacyReason(d.notice(),d.reason()));products.save(p);history(p,p.getMatchedRecallNoticeId(),d.status(),RegisteredProduct.RecallCheckStatus.SUCCESS,d.matched(),d.mismatched(),d.missing(),d.candidateUids(),d.reason(),d.queryType(),d.queryValue(),lookup);
  if(d.status()==RegisteredProduct.RecallDecisionStatus.RECALL_CONFIRMED&&previous!=d.status()&&d.notice()!=null&&!alerts.existsByRegisteredProductIdAndRecallNoticeIdAndAlertType(p.getId(),d.notice().getId(),"RECALL_CONFIRMED")){alerts.save(ProductRecallAlert.builder().registeredProductId(p.getId()).recallNoticeId(d.notice().getId()).alertType("RECALL_CONFIRMED").dryRun(properties.isDryRun()||!properties.isNotificationEnabled()).build());}return p;
 }
 private String effectiveBarcode(RegisteredProduct p){if(p.getBarcode()!=null)return p.getBarcode();String m=p.getModelNumber();return m!=null&&m.replaceAll("[\\s-]","").matches("\\d{8,14}")?m:null;}
 private String legacyReason(RecallNotice n,String fallback){if(n==null)return fallback;StringBuilder b=new StringBuilder();append(b,"제품 결함",n.getDefectDescription());append(b,"위해 정보",n.getHazardDescription());append(b,"소비자 행동요령",n.getConsumerAction());append(b,"문의처",n.getInquiryTel());return b.isEmpty()?fallback:b.toString();}private void append(StringBuilder b,String k,String v){if(v!=null&&!v.isBlank()){if(!b.isEmpty())b.append('\n');b.append(k).append(": ").append(v);}}
 private void history(RegisteredProduct p,Long n,RegisteredProduct.RecallDecisionStatus ds,RegisteredProduct.RecallCheckStatus cs,List<String>m,List<String>mm,List<String>miss,List<String>uids,String reason,String qt,String qv,SafetyKoreaRecallClient.Lookup l){histories.save(ProductRecallCheckHistory.builder().registeredProductId(p.getId()).recallNoticeId(n).decisionStatus(ds).checkStatus(cs).queryType(qt).queryValue(qv).matchedFields(m).mismatchedFields(mm).missingFields(miss).candidateRecallUids(uids).decisionReason(reason).externalResultCode(l.resultCode()).externalResultMessage(l.resultMessage()).errorCode(l.errorCode()).errorMessage(l.errorMessage()).productSnapshot(Map.of("productName",safe(p.getProductName()),"manufacturer",safe(p.getManufacturer()),"modelNumber",safe(p.getModelNumber()),"barcode",safe(p.getBarcode()),"certificationNumber",safe(p.getCertificationNumber()))).checkedAt(LocalDateTime.now()).build());}private String safe(String v){return v==null?"":v;}
}
